/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SaleItem = IDL.Record({
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'medicineId' : IDL.Text,
  'medicineName' : IDL.Text,
});
export const Category = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Medicine = IDL.Record({
  'id' : IDL.Text,
  'manufacturer' : IDL.Text,
  'expiryDate' : IDL.Int,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'batchNumber' : IDL.Text,
  'genericName' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'unitPrice' : IDL.Float64,
  'reorderLevel' : IDL.Nat,
});
export const Sale = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(SaleItem),
});
export const Supplier = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addMedicine' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
      ],
      [IDL.Text],
      [],
    ),
  'addSupplier' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSale' : IDL.Func(
      [IDL.Text, IDL.Vec(SaleItem), IDL.Float64],
      [IDL.Text],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteMedicine' : IDL.Func([IDL.Text], [], []),
  'deleteSupplier' : IDL.Func([IDL.Text], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getAllSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategory' : IDL.Func([IDL.Text], [Category], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'lowStockCount' : IDL.Nat,
          'totalMedicines' : IDL.Nat,
          'totalCategories' : IDL.Nat,
          'expiringSoonCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getExpiringMedicines' : IDL.Func([IDL.Nat], [IDL.Vec(Medicine)], ['query']),
  'getLowStockMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getMedicine' : IDL.Func([IDL.Text], [Medicine], ['query']),
  'getSale' : IDL.Func([IDL.Text], [Sale], ['query']),
  'getSalesByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Sale)],
      ['query'],
    ),
  'getSupplier' : IDL.Func([IDL.Text], [Supplier], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchMedicines' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
  'updateCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateMedicine' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateSupplier' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SaleItem = IDL.Record({
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'medicineId' : IDL.Text,
    'medicineName' : IDL.Text,
  });
  const Category = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const Medicine = IDL.Record({
    'id' : IDL.Text,
    'manufacturer' : IDL.Text,
    'expiryDate' : IDL.Int,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'batchNumber' : IDL.Text,
    'genericName' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'unitPrice' : IDL.Float64,
    'reorderLevel' : IDL.Nat,
  });
  const Sale = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(SaleItem),
  });
  const Supplier = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addMedicine' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
        ],
        [IDL.Text],
        [],
      ),
    'addSupplier' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSale' : IDL.Func(
        [IDL.Text, IDL.Vec(SaleItem), IDL.Float64],
        [IDL.Text],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteMedicine' : IDL.Func([IDL.Text], [], []),
    'deleteSupplier' : IDL.Func([IDL.Text], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getAllSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategory' : IDL.Func([IDL.Text], [Category], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'lowStockCount' : IDL.Nat,
            'totalMedicines' : IDL.Nat,
            'totalCategories' : IDL.Nat,
            'expiringSoonCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getExpiringMedicines' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Medicine)],
        ['query'],
      ),
    'getLowStockMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getMedicine' : IDL.Func([IDL.Text], [Medicine], ['query']),
    'getSale' : IDL.Func([IDL.Text], [Sale], ['query']),
    'getSalesByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Sale)],
        ['query'],
      ),
    'getSupplier' : IDL.Func([IDL.Text], [Supplier], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchMedicines' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
    'updateCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateMedicine' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateSupplier' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };