/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'name' : string, 'description' : string }
export interface Medicine {
  'id' : string,
  'manufacturer' : string,
  'expiryDate' : bigint,
  'name' : string,
  'isActive' : boolean,
  'batchNumber' : string,
  'genericName' : string,
  'quantity' : bigint,
  'category' : string,
  'unitPrice' : number,
  'reorderLevel' : bigint,
}
export interface Sale {
  'id' : string,
  'customerName' : string,
  'totalAmount' : number,
  'timestamp' : bigint,
  'items' : Array<SaleItem>,
}
export interface SaleItem {
  'quantity' : bigint,
  'unitPrice' : number,
  'medicineId' : string,
  'medicineName' : string,
}
export interface Supplier {
  'id' : string,
  'name' : string,
  'contactPerson' : string,
  'isActive' : boolean,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string, string], undefined>,
  'addMedicine' : ActorMethod<
    [string, string, string, string, string, bigint, bigint, number, bigint],
    string
  >,
  'addSupplier' : ActorMethod<[string, string, string, string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSale' : ActorMethod<[string, Array<SaleItem>, number], string>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteMedicine' : ActorMethod<[string], undefined>,
  'deleteSupplier' : ActorMethod<[string], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllMedicines' : ActorMethod<[], Array<Medicine>>,
  'getAllSales' : ActorMethod<[], Array<Sale>>,
  'getAllSuppliers' : ActorMethod<[], Array<Supplier>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategory' : ActorMethod<[string], Category>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'lowStockCount' : bigint,
      'totalMedicines' : bigint,
      'totalCategories' : bigint,
      'expiringSoonCount' : bigint,
    }
  >,
  'getExpiringMedicines' : ActorMethod<[bigint], Array<Medicine>>,
  'getLowStockMedicines' : ActorMethod<[], Array<Medicine>>,
  'getMedicine' : ActorMethod<[string], Medicine>,
  'getSale' : ActorMethod<[string], Sale>,
  'getSalesByDateRange' : ActorMethod<[bigint, bigint], Array<Sale>>,
  'getSupplier' : ActorMethod<[string], Supplier>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchMedicines' : ActorMethod<[string], Array<Medicine>>,
  'updateCategory' : ActorMethod<[string, string], undefined>,
  'updateMedicine' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      number,
      bigint,
      boolean,
    ],
    undefined
  >,
  'updateSupplier' : ActorMethod<
    [string, string, string, string, string, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];